/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfinal;

import IOBD.Conexion;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author Alex Recacha
 */
public class VentanaAlumno extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAlumno
     *
     * @param usuario recibe el nombre de usuario
     * @param reservas recibe el HashMap de reservas
     * @param a recibe un alumno
     * @param vProfesor recibe el ArrayList de profesores
     */
    public VentanaAlumno(String usuario, HashMap reservas, Alumno a, ArrayList<Profesor> vProfesor) {
        initComponents();
        this.c = new Conexion();
        jSliderInicioManana.setEnabled(false);
        jSliderFinManana.setEnabled(false);
        jSliderInicioTarde.setEnabled(false);
        jSliderFinTarde.setEnabled(false);
        this.usuario = usuario;
        jLabel5.setText(usuario);
        this.reservas = reservas;
        this.alumno = a;
        this.vProfesor = vProfesor;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSliderInicioManana = new javax.swing.JSlider();
        jSliderInicioTarde = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSliderFinManana = new javax.swing.JSlider();
        jSliderFinTarde = new javax.swing.JSlider();
        jRadioButtonMañana = new javax.swing.JRadioButton();
        jRadioButtonTarde = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonReservar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSliderInicioManana.setMajorTickSpacing(1);
        jSliderInicioManana.setMaximum(12);
        jSliderInicioManana.setMinimum(8);
        jSliderInicioManana.setMinorTickSpacing(1);
        jSliderInicioManana.setPaintLabels(true);
        jSliderInicioManana.setPaintTicks(true);
        jSliderInicioManana.setToolTipText("");
        jSliderInicioManana.setValue(8);
        jSliderInicioManana.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSliderInicioTarde.setMajorTickSpacing(1);
        jSliderInicioTarde.setMaximum(20);
        jSliderInicioTarde.setMinimum(16);
        jSliderInicioTarde.setMinorTickSpacing(1);
        jSliderInicioTarde.setPaintLabels(true);
        jSliderInicioTarde.setPaintTicks(true);
        jSliderInicioTarde.setToolTipText("");
        jSliderInicioTarde.setValue(16);
        jSliderInicioTarde.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Elige una hora de inicio");

        jLabel2.setText("Elige una hora de fin");

        jLabel3.setText("Aquí puedes reservar prácticas de coche");

        jSliderFinManana.setMajorTickSpacing(1);
        jSliderFinManana.setMaximum(12);
        jSliderFinManana.setMinimum(8);
        jSliderFinManana.setMinorTickSpacing(1);
        jSliderFinManana.setPaintLabels(true);
        jSliderFinManana.setPaintTicks(true);
        jSliderFinManana.setToolTipText("");
        jSliderFinManana.setValue(8);
        jSliderFinManana.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSliderFinTarde.setMajorTickSpacing(1);
        jSliderFinTarde.setMaximum(20);
        jSliderFinTarde.setMinimum(16);
        jSliderFinTarde.setMinorTickSpacing(1);
        jSliderFinTarde.setPaintLabels(true);
        jSliderFinTarde.setPaintTicks(true);
        jSliderFinTarde.setToolTipText("");
        jSliderFinTarde.setValue(16);
        jSliderFinTarde.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(jRadioButtonMañana);
        jRadioButtonMañana.setText("Mañana");
        jRadioButtonMañana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMañanaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonTarde);
        jRadioButtonTarde.setText("Tarde");
        jRadioButtonTarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTardeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Bienvenido,");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButtonReservar.setText("Reservar");
        jButtonReservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonReservarMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jRadioButtonMañana)
                        .addGap(27, 27, 27)
                        .addComponent(jRadioButtonTarde)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSliderInicioManana, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSliderFinManana, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSliderInicioTarde, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSliderFinTarde, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jButtonReservar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTarde)
                    .addComponent(jRadioButtonMañana))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSliderInicioManana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderFinManana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSliderInicioTarde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderFinTarde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMañanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMañanaActionPerformed

        jSliderInicioManana.setEnabled(true);
        jSliderFinManana.setEnabled(true);
        jSliderInicioTarde.setEnabled(false);
        jSliderFinTarde.setEnabled(false);

    }//GEN-LAST:event_jRadioButtonMañanaActionPerformed

    private void jRadioButtonTardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTardeActionPerformed
        jSliderInicioTarde.setEnabled(true);
        jSliderFinTarde.setEnabled(true);
        jSliderInicioManana.setEnabled(false);
        jSliderFinManana.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonTardeActionPerformed

    private void jButtonReservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReservarMouseClicked

        boolean libre = true;
        int ran = (int) (Math.floor(Math.random() * vProfesor.size()) + 1);

        if (jRadioButtonMañana.isSelected() && (jSliderInicioManana.getValue() != jSliderFinManana.getValue())) {
            Reserva r = new Reserva(jSliderInicioManana.getValue(), jSliderFinManana.getValue(), c.consultarCodigoAlumno(usuario), ran);
            Collection aux = reservas.values();
            Iterator it = aux.iterator();
            while (it.hasNext()) {
                Reserva re = (Reserva) it.next();
                if (re.getHoraI() == r.getHoraI() && re.getHoraF() == r.getHoraF()) {
                    libre = false;
                }
            }
            if (libre) {
                //reservas.put(reservas.size()+1, r);
                c.insertarReserva(jSliderInicioManana.getValue(), jSliderFinManana.getValue(), c.consultarCodigoAlumno(usuario), ran);
                horasReservadas += r.toString() + "\n";

            } else {
                JOptionPane.showMessageDialog(this, "Franja horaria ocupada.");
            }
        } else if (jSliderInicioTarde.getValue() != jSliderFinTarde.getValue()) {
            Reserva r = new Reserva(jSliderInicioTarde.getValue(), jSliderFinTarde.getValue(), c.consultarCodigoAlumno(usuario), c.consultarCodigoProfesor(usuario));
            Collection aux = reservas.values();
            Iterator it = aux.iterator();
            while (it.hasNext()) {
                Reserva re = (Reserva) it.next();
                if (re.getHoraI() == r.getHoraI() && re.getHoraF() == r.getHoraF()) {
                    libre = false;
                }
            }
            if (libre) {
                //reservas.put(reservas.size()+1, r);
                horasReservadas += r.toString() + "\n";
                c.insertarReserva(jSliderInicioTarde.getValue(), jSliderFinTarde.getValue(), c.consultarCodigoAlumno(usuario), ran);
            } else {
                JOptionPane.showMessageDialog(this, "Franja horaria ocupada.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No pongas la misma hora inicio de fin.");
        }

        String[] vLista = new String[reservas.size()];
        int contador = 0;
        reservas = c.cargarReservas();
        Collection aux = reservas.values();
        Iterator it = aux.iterator();
        while (it.hasNext()) {
            Reserva re = (Reserva) it.next();
            vLista[contador] = re.toString();
            contador++;
        }
        JList lista = new JList(vLista);


    }//GEN-LAST:event_jButtonReservarMouseClicked
    private DefaultListModel crearLista() {
        DefaultListModel<String> model = new DefaultListModel<>();
        Collection aux = reservas.values();
        Iterator it = aux.iterator();
        while (it.hasNext()) {
            Reserva re = (Reserva) it.next();
            model.addElement(re.toString());
        }
        return model;
    }

    private Conexion c;
    private String horasReservadas;
    private ArrayList<Profesor> vProfesor;
    private Alumno alumno;
    private HashMap<Integer, Reserva> reservas;
    private String usuario;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonReservar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButtonMañana;
    private javax.swing.JRadioButton jRadioButtonTarde;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSliderFinManana;
    private javax.swing.JSlider jSliderFinTarde;
    private javax.swing.JSlider jSliderInicioManana;
    private javax.swing.JSlider jSliderInicioTarde;
    // End of variables declaration//GEN-END:variables
}
