/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfinal;

import IOBD.Conexion;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author Alex Recacha
 */
public class VentanaAlumno extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAlumno
     *
     * @param usuario recibe el nombre de usuario
     * @param reservas recibe el HashMap de reservas
     * @param a recibe un alumno
     * @param vProfesor recibe el ArrayList de profesores
     */
    public VentanaAlumno(String usuario, HashMap reservas, Alumno a, ArrayList<Profesor> vProfesor) {
        initComponents();
        this.c = new Conexion();
        jSliderInicioManana.setEnabled(false);
        jSliderFinManana.setEnabled(false);
        jSliderInicioTarde.setEnabled(false);
        jSliderFinTarde.setEnabled(false);
        this.usuario = usuario;
        jLabel5.setText(usuario);
        this.reservas = reservas;
        this.TodasReservas = c.cargarTodasLasReservas();
        this.alumno = a;
        this.vProfesor = vProfesor;
        modelo = new DefaultListModel();
        jList1.setModel(modelo);
        crearLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSliderInicioManana = new javax.swing.JSlider();
        jSliderInicioTarde = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSliderFinManana = new javax.swing.JSlider();
        jSliderFinTarde = new javax.swing.JSlider();
        jRadioButtonMañana = new javax.swing.JRadioButton();
        jRadioButtonTarde = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonReservar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        modelo = new DefaultListModel();
        jList1 = new javax.swing.JList<>();
        jButtonDesconectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSliderInicioManana.setMajorTickSpacing(1);
        jSliderInicioManana.setMaximum(12);
        jSliderInicioManana.setMinimum(8);
        jSliderInicioManana.setMinorTickSpacing(1);
        jSliderInicioManana.setPaintLabels(true);
        jSliderInicioManana.setPaintTicks(true);
        jSliderInicioManana.setToolTipText("");
        jSliderInicioManana.setValue(8);
        jSliderInicioManana.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSliderInicioTarde.setMajorTickSpacing(1);
        jSliderInicioTarde.setMaximum(20);
        jSliderInicioTarde.setMinimum(16);
        jSliderInicioTarde.setMinorTickSpacing(1);
        jSliderInicioTarde.setPaintLabels(true);
        jSliderInicioTarde.setPaintTicks(true);
        jSliderInicioTarde.setToolTipText("");
        jSliderInicioTarde.setValue(16);
        jSliderInicioTarde.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Elige una hora de inicio");

        jLabel2.setText("Elige una hora de fin");

        jLabel3.setText("Aquí puedes reservar prácticas de coche");

        jSliderFinManana.setMajorTickSpacing(1);
        jSliderFinManana.setMaximum(12);
        jSliderFinManana.setMinimum(8);
        jSliderFinManana.setMinorTickSpacing(1);
        jSliderFinManana.setPaintLabels(true);
        jSliderFinManana.setPaintTicks(true);
        jSliderFinManana.setToolTipText("");
        jSliderFinManana.setValue(8);
        jSliderFinManana.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSliderFinTarde.setMajorTickSpacing(1);
        jSliderFinTarde.setMaximum(20);
        jSliderFinTarde.setMinimum(16);
        jSliderFinTarde.setMinorTickSpacing(1);
        jSliderFinTarde.setPaintLabels(true);
        jSliderFinTarde.setPaintTicks(true);
        jSliderFinTarde.setToolTipText("");
        jSliderFinTarde.setValue(16);
        jSliderFinTarde.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(jRadioButtonMañana);
        jRadioButtonMañana.setText("Mañana");
        jRadioButtonMañana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMañanaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonTarde);
        jRadioButtonTarde.setText("Tarde");
        jRadioButtonTarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTardeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Bienvenid@,");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButtonReservar.setText("Reservar");
        jButtonReservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonReservarMouseClicked(evt);
            }
        });

        jList1.setModel(modelo);
        jScrollPane2.setViewportView(jList1);

        jButtonDesconectar.setText("Desconectar");
        jButtonDesconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDesconectarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSliderInicioManana, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jSliderInicioTarde, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderFinTarde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSliderFinManana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonMañana)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(jRadioButtonTarde)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jButtonReservar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonDesconectar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTarde)
                    .addComponent(jRadioButtonMañana)
                    .addComponent(jButtonDesconectar))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSliderInicioManana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderFinManana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSliderInicioTarde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderFinTarde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMañanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMañanaActionPerformed

        jSliderInicioManana.setEnabled(true);
        jSliderFinManana.setEnabled(true);
        jSliderInicioTarde.setEnabled(false);
        jSliderFinTarde.setEnabled(false);

    }//GEN-LAST:event_jRadioButtonMañanaActionPerformed

    private void jRadioButtonTardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTardeActionPerformed
        jSliderInicioTarde.setEnabled(true);
        jSliderFinTarde.setEnabled(true);
        jSliderInicioManana.setEnabled(false);
        jSliderFinManana.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonTardeActionPerformed

    private void jButtonReservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReservarMouseClicked

        boolean libre = true;
        int ran = (int) (Math.floor(Math.random() * vProfesor.size()) + 1);
        
        if (jRadioButtonMañana.isSelected() && (jSliderInicioManana.getValue() != jSliderFinManana.getValue())) {
            jList1.removeAll();
            Reserva r = new Reserva(jSliderInicioManana.getValue(), jSliderFinManana.getValue(), c.consultarCodigoAlumno(usuario), ran);
            Collection aux = TodasReservas.values();
            Iterator it = aux.iterator();
            while (it.hasNext()) {
                Reserva re = (Reserva) it.next();
                if ((re.getHoraI() == r.getHoraI() || re.getHoraF() == r.getHoraF()) && re.getProfesor() == r.getProfesor()) {
                    libre = false;
                }
            }
            if (libre) {
                c.insertarReserva(jSliderInicioManana.getValue(), jSliderFinManana.getValue(), c.consultarCodigoAlumno(usuario), ran);
                ran = 0;
                crearLista();
            } else {
                JOptionPane.showMessageDialog(this, "Franja horaria ocupada.");
            }
        }
        if (jRadioButtonTarde.isSelected() && (jSliderInicioTarde.getValue() != jSliderFinTarde.getValue())) {
            jList1.removeAll();
            Reserva r = new Reserva(jSliderInicioTarde.getValue(), jSliderFinTarde.getValue(), c.consultarCodigoAlumno(usuario), c.consultarCodigoProfesor(usuario));
            Collection aux = TodasReservas.values();
            Iterator it = aux.iterator();
            while (it.hasNext()) {
                Reserva re = (Reserva) it.next();
                if ((re.getHoraI() == r.getHoraI() || re.getHoraF() == r.getHoraF()) && re.getProfesor() == r.getProfesor()) {
                    libre = false;
                }
            }
            if (libre) {
                c.insertarReserva(jSliderInicioTarde.getValue(), jSliderFinTarde.getValue(), c.consultarCodigoAlumno(usuario), ran);
                ran = 0;
                crearLista();
            } else {
                JOptionPane.showMessageDialog(this, "Franja horaria ocupada.");
            }
        }

        

    }//GEN-LAST:event_jButtonReservarMouseClicked

    private void jButtonDesconectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDesconectarMouseClicked
        Autoescuela a = new Autoescuela();
        a.setLocationRelativeTo(this);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonDesconectarMouseClicked
    private void crearLista() {
        reservas = c.cargarReservasAlumno(usuario);
        Collection aux = reservas.values();
        Iterator it = aux.iterator();
        while (it.hasNext()) {
            Reserva re = (Reserva) it.next();
            modelo.addElement(re.toString());
        }

    }

    private Conexion c;
    private String horasReservadas;
    private ArrayList<Profesor> vProfesor;
    private Alumno alumno;
    private HashMap<Integer, Reserva> reservas;
    private HashMap<Integer, Reserva> TodasReservas;
    private String usuario;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonDesconectar;
    private javax.swing.JButton jButtonReservar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private DefaultListModel modelo;
    private javax.swing.JRadioButton jRadioButtonMañana;
    private javax.swing.JRadioButton jRadioButtonTarde;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSliderFinManana;
    private javax.swing.JSlider jSliderFinTarde;
    private javax.swing.JSlider jSliderInicioManana;
    private javax.swing.JSlider jSliderInicioTarde;
    // End of variables declaration//GEN-END:variables
}
